### ISSUE TITLE
(context for) sshkey support?

### ISSUE THREAD

**Issue by j-c-h-e-n-g** [pendrica/chef-provisioning-azurerm#10]
It appears wild, reckless promises have been made in the chef-provisioning-azure readme.md: `# Until SSH keys are supported (soon)`

How soon is soon? :) 

 Will chef-provisioning-azure-rm support it? Or it's because `azure-sdk-for-ruby` doesn't support it?

**Comment by stuartpreston** [comment]
Yes, initially this was down to ```azure-sdk-for-ruby``` (for the chef-provisioning-azure driver, which uses a completely different approach to chef-provisioning-azurerm).  With chef-provisioning-azurerm, the machines are not bootstrapped through the front end, instead the Chef VM Extension is optionally applied to each compute resource that is created. 

As ARM supports the upload of the public key to the servers (see https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-sshkey/azuredeploy.json#L156-L165 for an example configuration), this will work fine with chef-provisioning-azurerm. However your recipe will need to load the public key data to be specified as a string parameter.

**Comment by stuartpreston** [comment]
Closing this as a solution has been supplied for ARM templates. Please reopen if you have further questions.
