### ISSUE TITLE
Questions after reading documentation, before giving it a try

### ISSUE THREAD

**Issue by mhedgpeth** [pendrica/chef-provisioning-azurerm#13]
I'm trying to easily create a development environment with chef, and I have a small application with 2 load-balanced IIS nodes and a database node with a windows service running on it. After reading through your documentation I'm left with a few questions I thought you might help me with:

1) Does this process support Policyfiles?

2) Why wouldn't I use the azure provisioning plugin listed on the chef site? (keep in mind my understanding of azure is very limited)

3) Are you saying the nodes I provision must have access to a Chef Server in order to fully converge? I'm not sure what you mean by the nodes not bootstrapping; it would seem that is what they would have to do in order to be provisioned.

4) How would you provision the database (i.e., restore from a backup from a particular location)? This is not a production use case for us, but in a development environment we would want to restore the database from backup. Also, I suppose, we would use a SQL Server image so we wouldn't have to worry about that part.

5) Do you still create a provision cookbook and then run it on your ChefDK node in local mode to get started?

6) Are the resources you create here idempotent? I didn't know what you meant by only Microsoft.Compute resources on the Chef Server.

Thanks for your great work. I seem to be following you around github. :)

**Comment by stuartpreston** [comment]
Hi there
Quick answers as I'm on the move, maybe best to drop an email ;)
1. Policyfiles should work as they are in the 

In my world we have 3 concerns:
   1. Provisioning - about spinning up VMs and connecting them to Chef 
   2. Config Management - about configuring the machine once connected to Chef
   3. Release Management/Deployment - about putting the application payload on after (1) and (2)

I'm not well up on the process of running Policyfiles, but would like to know how it fits. I know you can "provision" using a Policyfile but that doesn't really apply with Chef Provisioning.

2. The Azure plugin still plugged on the Chef site still refers to the Service Management (v1 Portal) features of Azure, and do not work with Azure Resource Manager.

3. Yes you must run Chef Provisioning from a client that has access to it's validator key as this is transferred to the machines and is then used to create a client correctly via adding the Chef VM Extension 

4. Yes, the same way you would deal with any other database really (perhaps designating a node that runs that scripts) - though really I put this into (3) Release Management concerns.

5. You can't run in Local Mode without some hacking (see the validation key requirement - the Chef VM Extension needs to talk to an accessible server). 

6. Chef Provisioning isn't creating the resources itself - it is taking your ARM deployment template JSON, adding the Chef client and sending it to the server.  In that sense, ARM JSON templates are supposed to be idempotent within Azure.

Probably best to email me directly - happy to run some sort of demo on this if necessary.  Thanks.

**Comment by stuartpreston** [comment]
Closing this for now, feel free to re-open with new issues if necessary.
