### ISSUE TITLE
Storage Provisioning not working

### ISSUE THREAD

**Issue by anshulp25** [pendrica/chef-provisioning-azurerm#14]
Hi, 
I am trying to provision the following storage.

```
require 'chef/provisioning/azurerm'
with_driver 'AzureRM:abcde-1234-5678-efghi-123235235'



azure_storage_account 'mystorageaccount02' do
  resource_group 'chef_provisioning_azurerm'
  location 'Central US'
  account_type 'Standard_LRS'
end
```

But I am getting following error

```
MsRestAzure::AzureOperationError: azure_storage_account[mystorageaccount02] (@recipe_files::C:/Users/anshulp/Desktop/example.rb line 6) had an error: MsRestAzure::AzureOperationError: MsRestAzure::AzureOperationError
```

I am able to provision the same via CLI 

Please help.

**Comment by stuartpreston** [comment]
I verified this by adding extra error handling, it seems the storage account will be created (as long the name is globally unique) however the additional info (tags, custom domain etc. are failing currently).

Adding extra debug I got the actual error being returned:

```
[2016-06-08T00:07:09+02:00] FATAL: RuntimeError: azure_storage_account[pendricastr6d5f3] (chef-provisioning-azurerm-examples::default line 14) had an error: RuntimeError: MustSpecifyPropertyToUpdate: Request must specify an account property to update.
```

This looks like something in Azure's provider has changed recently.  We will investigate.

**Comment by stuartpreston** [comment]
This is now merged and will be in the next build
