### ISSUE TITLE
Knife azurerm server create - ERROR Node already exists 

### ISSUE THREAD

**Issue by hvillavicencio** [pendrica/chef-provisioning-azurerm#16]
Hi all,
I have configure everything needed , but I have a problem when I run the command for VM creation.
It seems like he VM name already exists, but that is not true
what could be the issue

**Comment by stuartpreston** [comment]
I think you might be looking for the Knife Azure repo which is at: https://github.com/chef/knife-azure/ - please re-post your question there (and would be useful to post the full command line and error messages seen).
