### ISSUE TITLE
name error : uninitialized constant Azure::ARM

### ISSUE THREAD

**Issue by danielprashanth** [pendrica/chef-provisioning-azurerm#26]
when running chef-client by using this recipe as default recipe i am getting 
name error : uninitialized constant Azure::ARM

**Comment by stuartpreston** [comment]
This is believed to be because a later version of the Azure SDK for Ruby has a breaking change.  If you are able to pin the version of any `azure_mgmt_*` resources to version 0.14.0 then I think this will succeed.  We will investigate updating this repo to use the latest version (v0.15.1 upwards).

**Comment by stuartpreston** [comment]
Please could you try with the latest chef-provisioning-azurerm gem, which should be version 0.6.1

**Comment by danielprashanth** [comment]
thanks for the reply . I have tried with  chef-provisioning-azurerm gem
version 0.6.1 and azure sdk version 0.4.0 and im not getting this error
anymore .

cheers.
