### ISSUE TITLE
chef-provisioning-azurerm is failing with latest chefdk

### ISSUE THREAD

**Issue by pritam97** [pendrica/chef-provisioning-azurerm#30]
Hi Team, 

I have installed chefdf3.9.0 version, which will installed kitchen-azurerm as default. 
# chef -v
Chef Development Kit Version: 3.9.0
chef-client version: 14.12.3
delivery version: master (9d07501a3b347cc687c902319d23dc32dd5fa621)
berks version: 7.0.8
kitchen version: 1.24.0
inspec version: 3.9.3

# chef gem list |grep azure
azure_graph_rbac (0.17.1)
azure_mgmt_compute (0.14.0)
azure_mgmt_key_vault (0.17.3)
azure_mgmt_network (0.18.6, 0.18.4, 0.14.0)
azure_mgmt_resources (0.17.3, 0.17.2, 0.14.0)
azure_mgmt_storage (0.14.0)
chef-provisioning-azurerm (0.6.1)
kitchen-azurerm (0.14.8)
ms_rest_azure (0.11.0, 0.9.0)
I have all required gem for running chef-provisioning-azurerm gem. 

but when i execute below recipe 

require 'chef/provisioning/azurerm'
with_driver 'AzureRM:<Subscription ID >'

azure_resource_group 'pritamtestrg' do
  location 'East US 2'
  tags businessUnit: 'IT'
end
-----------------------------------------------
i am getting below error can you help us to resolve. 

Gem::ConflictError
------------------
Unable to activate chef-provisioning-azurerm-0.6.1, because azure_mgmt_resources-0.17.3 conflicts with azure_mgmt_resources (= 0.14.0, ~> 0.14), azure_mgmt_network-0.18.6 conflicts with azure_mgmt_network (= 0.14.0, ~> 0.14)

Regards,
Pritam K

**Comment by stuartpreston** [comment]
Hi - there's no team here I'm afraid! chef-provisioning-azurerm is not under maintainance or supported by Chef.

My guess would be that the wrong dependencies are listed in the chef-client binstub that is being executed from the embedded/bin folder on your system, and you should remove all but the following from it:

  spec.add_dependency 'azure_mgmt_resources', '~> 0.14', '= 0.14.0'
  spec.add_dependency 'azure_mgmt_storage', '~> 0.14', '= 0.14.0'
  spec.add_dependency 'azure_mgmt_compute', '~> 0.14', '= 0.14.0'
  spec.add_dependency 'azure_mgmt_network', '~> 0.14', '= 0.14.0'

**Comment by pritam97** [comment]
Hi , 
see below command output 

root@jkosalp-cep-dev:~# chef gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.9
  - RUBY VERSION: 2.5.5 (2019-03-15 patchlevel 157) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/chefdk/embedded/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /root/.chefdk/gem/ruby/2.5.0
  - RUBY EXECUTABLE: /opt/chefdk/embedded/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/chefdk/embedded/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/chefdk/embedded/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     **- /opt/chefdk/embedded/lib/ruby/gems/2.5.0
     - /root/.chefdk/gem/ruby/2.5.0**
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--user --no-document"
     - "update" => "--user --no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /opt/chefdk/bin
     - /root/.chefdk/gem/ruby/2.5.0/bin
     - /opt/chefdk/embedded/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /snap/bin
     - /opt/chefdk/gitbin

/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems# ls -ld azur*
drwxrwxr-x 3 root root 4096 Apr 24 09:58 azure_graph_rbac-0.17.1
drwxrwxr-x 3 root root 4096 Apr 24 09:58 azure_mgmt_key_vault-0.17.3
drwxrwxr-x 3 root root 4096 Apr 24 09:58 azure_mgmt_network-0.18.6
drwxrwxr-x 3 root root 4096 Apr 24 09:58 azure_mgmt_resources-0.17.3

and 
~/.chefdk/gem/ruby/2.5.0/gems# ls -d *
azure_mgmt_compute-0.14.0  azure_mgmt_resources-0.14.0  chef-provisioning-azurerm-0.6.1  kitchen-azurerm-0.14.8
azure_mgmt_network-0.14.0  azure_mgmt_resources-0.17.2  excon-0.64.0                     ms_rest_azure-0.9.0
azure_mgmt_network-0.18.4  azure_mgmt_storage-0.14.0    jsonpath-1.0.1                   to_regexp-0.2.1

can you please tell me from where we should remove ? 

if we remove 0.14.0 version gem chef-provisioning-azurerm will stop if i delete 0.17.0 version then kitchen-azurerm will stop. 

can you please suggest how to proceed.

**Comment by stuartpreston** [comment]
Have a look in (I think) /opt/chefdk/embedded/bin
Find the file called chef-client and have a look at the *content* of the file. You'll see that it eagerly loads specific versions of the gems in there, simply comment out any azure-related ones from there

**Comment by pritam97** [comment]
Hi , 

this is file 

#!/opt/chefdk/embedded/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'chef' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('chef', 'chef-client', version)
else
gem "chef", version
load Gem.bin_path("chef", "chef-client", version)
end
 

I tried to comment out but still same error.

**Comment by stuartpreston** [comment]
That doesn't look like the file that comes with the distribution as it doesn't have any version numbers of dependencies in it.. Have a look and see if there are other chef-client binstub files on your system that could be used. (`which chef-client` ?)

**Comment by pritam97** [comment]
cat /opt/chefdk/bin/chef-client
#!/opt/chefdk/embedded/bin/ruby --disable-gems
#--APP_BUNDLER_BINSTUB_FORMAT_VERSION=1--
require "rubygems"

begin
  # this works around rubygems/rubygems#2196 and can be removed in rubygems > 2.7.6
  require "rubygems/bundler_version_finder"
rescue LoadError
  # probably means rubygems is too old or too new to have this class, and we don't care
end

# avoid appbundling if we are definitely running within a Bundler bundle.
# most likely the check for defined?(Bundler) is enough since we don't require
# bundler above, but just for paranoia's sake also we test to see if Bundler is
# really doing its thing or not.
unless defined?(Bundler) && Bundler.instance_variable_defined?("@load")
  ENV["GEM_HOME"] = ENV["GEM_PATH"] = nil unless ENV["APPBUNDLER_ALLOW_RVM"] == "true"
  ::Gem.clear_paths

  gem "activesupport", "= 5.2.3"
  gem "addressable", "= 2.5.2"
  gem "app_conf", "= 0.4.2"
  gem "appbundler", "= 0.12.0"
  gem "artifactory", "= 3.0.0"
  gem "ast", "= 2.4.0"
  gem "aws-eventstream", "= 1.0.2"
  gem "aws-sdk", "= 2.11.256"
  gem "aws-sdk-core", "= 2.11.256"
  gem "aws-sdk-resources", "= 2.11.256"
  gem "aws-sigv4", "= 1.1.0"
  gem "axiom-types", "= 0.1.1"
#  gem "azure_graph_rbac", "= 0.17.1"
#  gem "azure_mgmt_key_vault", "= 0.17.3"
# gem "azure_mgmt_network", "= 0.18.6"
# gem "azure_mgmt_resources", "= 0.17.3"
  gem "backports", "= 3.13.0"
  gem "berkshelf", "= 7.0.8"
  gem "binding_of_caller", "= 0.8.0"
  gem "builder", "= 3.2.3"
  gem "byebug", "= 11.0.1"
  gem "chef", "= 14.12.3"
  gem "chef", "= 14.12.3"
  gem "chef-api", "= 0.9.0"
  gem "chef-apply", "= 0.2.8"
  gem "chef-config", "= 14.12.3"
  gem "chef-dk", "= 3.9.0"
  gem "chef-provisioning", "= 2.7.6"
  gem "chef-provisioning-aws", "= 3.0.7"
  gem "chef-provisioning-fog", "= 0.26.3"
  gem "chef-sugar", "= 5.0.1"
  gem "chef-telemetry", "= 0.1.8"
  gem "chef-vault", "= 3.4.3"
  gem "chef-zero", "= 14.0.12"
  gem "cheffish", "= 14.0.4"
  gem "chefspec", "= 7.3.4"
  gem "chefstyle", "= 0.11.2"
  gem "citrus", "= 3.0.2"
  gem "cleanroom", "= 1.0.0"
  gem "coderay", "= 1.1.2"
  gem "coercible", "= 1.0.0"
  gem "concurrent-ruby", "= 1.1.5"
  gem "cookbook-omnifetch", "= 0.8.1"
  gem "cookstyle", "= 3.0.2"
  gem "cucumber", "= 3.1.2"
  gem "cucumber-core", "= 3.2.1"
  gem "cucumber-expressions", "= 6.0.1"
  gem "cucumber-tag_expressions", "= 1.1.1"
  gem "cucumber-wire", "= 0.0.1"
  gem "dco", "= 1.0.1"
  gem "debug_inspector", "= 0.0.3"
  gem "declarative", "= 0.0.10"
  gem "declarative-option", "= 0.1.0"
  gem "dep-selector-libgecode", "= 1.3.1"
  gem "dep_selector", "= 1.0.6"
  gem "descendants_tracker", "= 0.0.4"
  gem "diff-lcs", "= 1.3"
  gem "diffy", "= 3.3.0"
  gem "docker-api", "= 1.34.2"
  gem "domain_name", "= 0.5.20180417"
  gem "droplet_kit", "= 2.9.0"
  gem "equalizer", "= 0.0.11"
  gem "equatable", "= 0.5.0"
  gem "erubis", "= 2.7.0"
  gem "excon", "= 0.64.0"
  gem "faraday", "= 0.15.4"
  gem "faraday-cookie_jar", "= 0.0.6"
  gem "faraday_middleware", "= 0.12.2"
  gem "fauxhai", "= 6.11.0"
  gem "ffi", "= 1.10.0"
  gem "ffi", "= 1.10.0"
  gem "ffi", "= 1.10.0"
  gem "ffi-libarchive", "= 0.4.6"
  gem "ffi-rzmq", "= 2.0.7"
  gem "ffi-rzmq-core", "= 1.0.7"
  gem "ffi-yajl", "= 2.3.1"
  gem "filesize", "= 0.1.1"
  gem "fog-aws", "= 2.0.1"
  gem "fog-core", "= 1.45.0"
  gem "fog-digitalocean", "= 0.4.0"
  gem "fog-joyent", "= 0.0.1"
  gem "fog-json", "= 1.2.0"
  gem "fog-openstack", "= 0.3.10"
  gem "fog-rackspace", "= 0.1.6"
  gem "fog-scaleway", "= 0.5.0"
  gem "fog-softlayer", "= 1.1.4"
  gem "fog-xenserver", "= 1.0.0"
  gem "fog-xml", "= 0.1.3"
  gem "foodcritic", "= 15.1.0"
  gem "formatador", "= 0.2.5"
  gem "fuzzyurl", "= 0.9.0"
  gem "gcewinpass", "= 1.1.0"
  gem "gherkin", "= 5.1.0"
  gem "git", "= 1.5.0"
  gem "google-api-client", "= 0.23.9"
  gem "googleauth", "= 0.6.7"
  gem "gssapi", "= 1.2.0"
  gem "guard", "= 2.15.0"
  gem "gyoku", "= 1.3.1"
  gem "hashie", "= 3.6.0"
  gem "highline", "= 1.7.10"
  gem "htmlentities", "= 4.3.4"
  gem "http", "= 2.2.2"
  gem "http-cookie", "= 1.0.3"
  gem "http-form_data", "= 1.0.3"
  gem "http_parser.rb", "= 0.6.0"
  gem "httpclient", "= 2.8.3"
  gem "i18n", "= 1.6.0"
  gem "ice_nine", "= 0.11.2"
  gem "inifile", "= 3.0.0"
  gem "iniparse", "= 1.4.4"
  gem "inspec", "= 3.9.3"
  gem "ipaddress", "= 0.8.3"
  gem "jmespath", "= 1.4.0"
  gem "json", "= 2.2.0"
  gem "jwt", "= 2.1.0"
  gem "kartograph", "= 0.2.7"
#  gem "kitchen-azurerm", "= 0.14.8"
  gem "kitchen-digitalocean", "= 0.10.3"
  gem "kitchen-dokken", "= 2.6.8"
  gem "kitchen-ec2", "= 2.5.0"
  gem "kitchen-google", "= 2.0.1"
  gem "kitchen-hyperv", "= 0.5.3"
  gem "kitchen-inspec", "= 1.1.0"
  gem "kitchen-vagrant", "= 1.5.1"
  gem "knife-acl", "= 1.0.3"
  gem "knife-cloud", "= 1.2.3"
  gem "knife-ec2", "= 0.19.16"
  gem "knife-google", "= 3.3.7"
  gem "knife-opc", "= 0.4.1"
  gem "knife-push", "= 1.1.2"
  gem "knife-spork", "= 1.7.2"
  gem "knife-tidy", "= 2.0.1"
  gem "knife-vsphere", "= 2.1.3"
  gem "knife-windows", "= 1.9.6"
  gem "libyajl2", "= 1.2.0"
  gem "listen", "= 3.1.5"
  gem "little-plugger", "= 1.1.4"
  gem "lockfile", "= 2.1.3"
  gem "logging", "= 2.2.2"
  gem "logify", "= 0.2.0"
  gem "lumberjack", "= 1.0.13"
  gem "memoist", "= 0.16.0"
  gem "method_source", "= 0.9.2"
  gem "mime-types", "= 3.2.2"
  gem "mime-types-data", "= 3.2019.0331"
  gem "mini_portile2", "= 2.4.0"
  gem "minitar", "= 0.8"
  gem "minitest", "= 5.10.3"
  gem "mixlib-archive", "= 1.0.1"
  gem "mixlib-archive", "= 1.0.1"
  gem "mixlib-authentication", "= 2.1.1"
  gem "mixlib-cli", "= 2.0.3"
  gem "mixlib-config", "= 2.2.18"
  gem "mixlib-install", "= 3.11.12"
  gem "mixlib-log", "= 3.0.1"
  gem "mixlib-shellout", "= 2.4.4"
  gem "mixlib-shellout", "= 2.4.4"
  gem "mixlib-versioning", "= 1.2.7"
  gem "molinillo", "= 0.6.6"
  gem "ms_rest", "= 0.7.3"
#  gem "ms_rest_azure", "= 0.11.0"
  gem "multi_json", "= 1.13.1"
  gem "multi_test", "= 0.1.2"
  gem "multipart-post", "= 2.0.0"
  gem "necromancer", "= 0.4.0"
  gem "nenv", "= 0.3.0"
  gem "net-scp", "= 1.2.1"
  gem "net-sftp", "= 2.1.2"
  gem "net-ssh", "= 4.2.0"
  gem "net-ssh-gateway", "= 1.3.0"
  gem "net-ssh-multi", "= 1.2.1"
  gem "net-telnet", "= 0.1.1"
  gem "netaddr", "= 1.5.1"
  gem "nokogiri", "= 1.10.2"
  gem "nokogiri", "= 1.10.2"
  gem "nokogiri", "= 1.10.2"
  gem "nori", "= 2.6.0"
  gem "notiffany", "= 0.1.1"
  gem "octokit", "= 4.14.0"
  gem "ohai", "= 14.8.11"
  gem "opscode-pushy-client", "= 2.5.6"
  gem "os", "= 1.0.0"
  gem "paint", "= 1.0.1"
  gem "parallel", "= 1.17.0"
  gem "parser", "= 2.6.2.1"
  gem "parslet", "= 1.8.2"
  gem "pastel", "= 0.7.2"
  gem "plist", "= 3.5.0"
  gem "polyglot", "= 0.3.5"
  gem "powerpack", "= 0.1.2"
  gem "proxifier", "= 1.0.3"
  gem "pry", "= 0.12.2"
  gem "pry-byebug", "= 3.7.0"
  gem "pry-remote", "= 0.1.8"
  gem "pry-stack_explorer", "= 0.4.9.3"
  gem "public_suffix", "= 3.0.3"
  gem "r18n-core", "= 3.2.0"
  gem "r18n-desktop", "= 3.2.0"
  gem "rack", "= 2.0.7"
  gem "rainbow", "= 3.0.0"
  gem "rake", "= 12.3.0"
  gem "rb-fsevent", "= 0.10.3"
  gem "rb-inotify", "= 0.10.0"
  gem "rb-readline", "= 0.5.5"
  gem "rbvmomi", "= 1.13.0"
  gem "rdoc", "= 6.0.1"
  gem "representable", "= 3.0.4"
  gem "resource_kit", "= 0.1.7"
  gem "retriable", "= 3.1.2"
  gem "retryable", "= 2.0.4"
  gem "rspec", "= 3.8.0"
  gem "rspec-core", "= 3.8.0"
  gem "rspec-expectations", "= 3.8.2"
  gem "rspec-its", "= 1.3.0"
  gem "rspec-mocks", "= 3.8.0"
  gem "rspec-support", "= 3.8.0"
  gem "rspec_junit_formatter", "= 0.2.3"
  gem "rubocop", "= 0.55.0"
  gem "ruby-prof", "= 0.17.0"
  gem "ruby-progressbar", "= 1.10.0"
  gem "ruby-shadow", "= 2.5.0"
  gem "ruby_dep", "= 1.5.0"
  gem "rubyntlm", "= 0.6.2"
  gem "rubyzip", "= 1.2.2"
  gem "rufus-lru", "= 1.1.0"
  gem "sawyer", "= 0.8.1"
  gem "semverse", "= 3.0.0"
  gem "serverspec", "= 2.41.3"
  gem "sfl", "= 2.3"
  gem "shellany", "= 0.0.1"
  gem "signet", "= 0.11.0"
  gem "slop", "= 3.6.0"
  gem "solve", "= 4.0.2"
  gem "specinfra", "= 2.77.0"
  gem "sshkey", "= 1.9.0"
  gem "sslshake", "= 1.3.0"
  gem "stove", "= 7.1.0"
  gem "strings", "= 0.1.5"
  gem "strings-ansi", "= 0.1.0"
  gem "syslog-logger", "= 1.6.8"
  gem "systemu", "= 2.6.5"
  gem "term-ansicolor", "= 1.7.1"
#  gem "test-kitchen", "= 1.24.0"
  gem "thor", "= 0.20.3"
  gem "thread_safe", "= 0.3.6"
  gem "timeliness", "= 0.4.0"
  gem "timers", "= 4.3.0"
  gem "tins", "= 1.20.2"
  gem "toml-rb", "= 1.1.2"
  gem "tomlrb", "= 1.2.8"
  gem "train", "= 1.7.6"
  gem "train-habitat", "= 0.1.1"
  gem "treetop", "= 1.6.10"
  gem "trollop", "= 2.9.9"
  gem "tty-color", "= 0.4.3"
  gem "tty-cursor", "= 0.6.1"
  gem "tty-prompt", "= 0.18.1"
  gem "tty-reader", "= 0.5.0"
  gem "tty-screen", "= 0.6.5"
  gem "tty-spinner", "= 0.9.0"
  gem "tty-table", "= 0.10.0"
  gem "tzinfo", "= 1.2.5"
  gem "uber", "= 0.1.0"
  gem "ubuntu_ami", "= 0.4.2"
  gem "unf", "= 0.1.4"
  gem "unf_ext", "= 0.0.7.2"
  gem "unf_ext", "= 0.0.7.2"
  gem "unf_ext", "= 0.0.7.2"
  gem "unicode-display_width", "= 1.5.0"
  gem "unicode_utils", "= 1.4.0"
  gem "uuidtools", "= 2.1.5"
  gem "virtus", "= 1.0.5"
  gem "winrm", "= 2.3.1"
  gem "winrm-elevated", "= 1.1.1"
  gem "winrm-fs", "= 1.3.2"
  gem "wisper", "= 2.0.0"
  gem "wmi-lite", "= 1.0.2"
  gem "xmlrpc", "= 0.3.0"
  gem "yard", "= 0.9.19"
  gem "chef", "= 14.12.3"
  spec = Gem::Specification.find_by_name("chef", "= 14.12.3")
else
  spec = Gem::Specification.find_by_name("chef")
end

bin_file = spec.bin_file("chef-client")

Kernel.load(bin_file)

I have commented all related to azure still same issue

**Comment by stuartpreston** [comment]
.. and kitchen-azurerm? (it loads those other dependencies into the client that you don't want)

**Comment by pritam97** [comment]
yeah i have disabled kitchen-azurerm as well.

**Comment by stuartpreston** [comment]
I'm afraid that's all I can help with, it's possible other gems listed there are loading the azure_* gems transitively. It's trial and error from here, good luck.
