### ISSUE TITLE
First experiences

### ISSUE THREAD

**Issue by christinedraper** [pendrica/chef-provisioning-azurerm#5]
These are things that may easily be my misunderstanding, or problems with the chef extensions rather than this driver.

1. It's not obvious how to specify more than one recipe in the runlist, if that is even possible. Putting an array causes an error (because it's passed as a string due to the string interpolation). 
2. It seems that success is reported even when something fails. I had two examples.
   a. First, I specified an adminPassword that didnt meet the password requirements. The provisioning run succeeded, but in the Azure Portal the deployment failed. 
   b. Second, I started a Windows server successfully, but specified an  Ubuntu-specific recipe. The chef-client run must have failed, but I got no indication in either the provisioning run or the Azure Portal.

As a complete aside, I managed to trick it to run in local mode by copying the deployment template directly in the local_cache/cache directory!!

**Comment by stuartpreston** [comment]
@christinedraper Thanks for giving it a spin!

My initial comments are that (1) is possibly a bug, the extension itself is eventually supposed to take an array such as ```["recipe[getting-started]", "recipe[apt]"]``` and I think my intent was to have this specified as a comma separated list. I'll look into it and see if I can repro/update the readme. 

For (2) this is hopefully an experience we can make better. Currently success of the resource is driven by whether the deployment is 'accepted' by Azure irrespective of the result. I agree a failing deployment in the Azure should return a similar result to the driver. Will look into it. 

For (2b) unfortunately once the extension has been passed the info needed to be created we do not have sight of any recipe outcome. The driver is just a lightweight way of getting the client set up, we do not interact in any way with the deployed client or have a mechanism to retrieve the outcome from the initial run. Does that explain things better?

**Comment by christinedraper** [comment]
Thanks for the explanations. It's possible in (1) that it's just a documentation issue... I tried passing it an array rather than comma-separated list.  (2b) seems like a challenge. Is it something that the extension itself might address, or inherent in the way extensions work?

**Comment by stuartpreston** [comment]
@christinedraper It's inherent in the fact that extensions merely deploy a client and connect it to a Chef server, setting it to run as a cron job or a Windows service according to the platform. After this the Chef Client is on its own. There's no communication to or from the extension available from a provisioning run. I'll still take a look at (1) when I can and fix the docs or the code (or maybe both!)

**Comment by stuartpreston** [comment]
Closing this out due to staleness, thanks Christine for all your feedback!
