### ISSUE TITLE
VM extension JSON not formulated correctly 

### ISSUE THREAD

**Issue by stuartpreston** [pendrica/chef-provisioning-azurerm#6]
Using https://github.com/Azure/azure-quickstart-templates/tree/master/101-vm-with-rdp-port

Error seen from ARM after running through Chef Provisioning AzureRM:

```
statusMessage:{"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource '[concat(vm,'/', 'chefExtension')]' at line '1' and column '5190' is not valid: Template language expression 'concat(vm,'/', 'chefExtension')' is not supported..'."}}
```

Fix is probably to surround all machine_name with ' ' around here: https://github.com/pendrica/chef-provisioning-azurerm/blob/master/lib/chef/provider/azure_resource_template.rb#L52 
but needs testing on more templates before putting in the fix

**Comment by andrewelizondo** [comment]
yup! looks right.
https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#concat

**Comment by stuartpreston** [comment]
It's actually more nuanced than that. Some templates are substituting a variable() here, and I cannot surround that with ```''``` ... :)
